package = "Test Package"
version = "0.1.0"
lua = ">=5.1"

[description]
summary = "simple test pkg"
maintainer = "Cootshk"
labels = [ "test" ]
license = "GPL-3.0"

[dependencies]
argparse = "0.7.1-1"
# Add your dependencies here
# `busted = ">=2.0"`

[run]
args = [ "src/main.lua" ]

[build]
type = "builtin"
